export interface Question {
  "q-idx": number
  "q-str": string
  "a-tp": string
  checkboxes?: string[]
  radios?: string[]
}

// {"q-idx": 2, "q-str": "DUMMY Question.", "a-tp": "radio",    "radios":     ["DUMMY Answer 1", "DUMMY Answer 2"]},
// {"q-idx": 4, "q-str": "DUMMY Question.", "a-tp": "checkbox", "checkboxes": ["DUMMY Answer 1", "DUMMY Answer 2"]},

export const staticQuizData: Question[] = [
  {"q-idx": 1  , "q-str": "Which ongoing health situations apply to you? (Select all that apply)"                                                    , "a-tp": "checkbox", "checkboxes": ["Active cancer treatment", "Regular blood transfusions", "Kidney failure requiring dialysis", "Chronic breathing condition impacting daily activities", "Persistent swallowing difficulty affecting meals", "Complex or non-healing wounds / pressure injury care", "Recent injury or surgery affecting daily life", "Progressive memory or thinking changes", "Long-term condition needing monitoring/education (e.g., diabetes, heart failure, COPD)", "Serious illness where comfort is the main goal", "End-of-life care needs", "None of the above"]},
  {"q-idx": 2  , "q-str": "Do you currently use—or need help with—any of the following home medical equipment or devices? (Select all that apply)"   , "a-tp": "checkbox", "checkboxes": ["Oxygen equipment or nebulizer", "Ventilator/respirator or airway-clearance device", "Tracheostomy tube/care or suction machine", "Feeding tube (NGT or PEG) or feeding pump", "Ostomy (stoma) appliances/bags", "Urinary catheter or urosheath with drainage bag", "IV line (PICC/port/central line) or IV pump", "Dialysis equipment (peritoneal cycler or home hemodialysis machine)", "Regular wound-care dressings/supplies", "Mobility aids (cane, walker, wheelchair)", "Transfer devices (transfer belt or mechanical lift)", "Communication device/board (AAC)", "Home monitoring devices where you want help taking readings (BP/pulse/temp)", "None of the above"]},
  {"q-idx": 3  , "q-str": "How do you manage your medications at home? (Choose one)"                                                                 , "a-tp": "radio",    "radios":     ["I manage my medications on my own", "I'm okay most days but need help with reminders or organizing them", "I need a nurse to set up or give my medications (not injections)", "I need a nurse to give injections (e.g., insulin, biologics)", "I'm not sure — I'd like someone to review how I take my meds"]},
  {"q-idx": 4  , "q-str": "Which of these best matches your movement needs right now?"                                                               , "a-tp": "radio",    "radios":     ["I move well without pain or limits", "Pain or stiffness limits my movement (e.g., back/knee/shoulder); I want a plan to improve it", "I feel weak/deconditioned after illness/inactivity and want strength/endurance training", "I get dizzy or unsteady with turns or when standing; I want balance/vestibular support", "I'm recovering from an injury or surgery and want safe movement guidance"]},
  {"q-idx": 5  , "q-str": "Which situation sounds most like you at home?"                                                                            , "a-tp": "radio",    "radios":     ["I manage bathing, kitchen tasks, and transfers without issues", "Bath/shower, toilet, or bed/chair transfers feel risky; I want techniques/equipment", "Fatigue, shortness of breath, or limited reach makes cooking/laundry hard; I want energy-saving tips and simple tools", "I'd like a home safety review (bathroom/kitchen layout, hazards) and equipment recommendations", "I miss steps with meds/appointments/recipes and want planning & memory supports for daily life"]},
  {"q-idx": 6  , "q-str": "Which best describes eating and drinking for you?"                                                                        , "a-tp": "radio",    "radios":     ["I eat and drink normally without coughing or choking", "I cough with certain textures or thin liquids; I'd like safer-swallow strategies", "Food/liquid feels \"stuck\" or meals take much longer; I want an assessment and a plan", "After a recent illness/surgery, swallowing is harder; I want help choosing safe textures"]},
  {"q-idx": 7  , "q-str": "How much help do you need to move around at home (walking, standing, transfers)?"                                         , "a-tp": "radio",    "radios":     ["I'm independent", "I use a cane/walker or feel safer with someone nearby", "I need hands-on help for transfers/stairs", "I mainly use a wheelchair or need two people/a lift"]},
  {"q-idx": 8  , "q-str": "Do you need help getting to appointments or errands?"                                                                     , "a-tp": "radio",    "radios":     ["I manage on my own", "A ride or help with check-in would help", "I need support during the visit", "I need a full escort to manage each step"]},
  {"q-idx": 9  , "q-str": "How much help do you need with bathing, dressing, eating, or toileting?"                                                  , "a-tp": "radio",    "radios":     ["I handle these on my own", "Reminders or set-up help make it easier", "I need hands-on help for some tasks", "I need full assistance most days"]},
  {"q-idx": 10 , "q-str": "How much help do you need for household tasks (meal prep, grocery shopping, light cleaning, laundry, tidying)?"           , "a-tp": "radio",    "radios":     ["No help needed — I do these tasks on my own", "Some help — occasional support with one or two tasks (e.g., meal prep or laundry)", "Frequent help — I often need help keeping up with several tasks", "Regular scheduled help — I need consistent help each week"]},
  {"q-idx": 11 , "q-str": "Do you need help at night?"                                                                                               , "a-tp": "radio",    "radios":     ["No night help needed", "Sometimes need help to the bathroom or repositioning", "Often need overnight supervision or safety checks"]},
  {"q-idx": 12 , "q-str": "In the past week, have you had difficulty remembering things like appointments or names?"                                 , "a-tp": "radio",    "radios":     ["Yes", "No"]},
  {"q-idx": 13 , "q-str": "Do you often feel confused or disoriented (e.g., not knowing where you are or what day it is)?"                           , "a-tp": "radio",    "radios":     ["Never", "Occasionally", "Often"]},
  {"q-idx": 14 , "q-str": "Have others expressed concern about changes in your behavior or memory?"                                                  , "a-tp": "radio",    "radios":     ["Yes", "No", "Not sure"]},
  {"q-idx": 15 , "q-str": "Which of these fits your communication or day-to-day thinking?"                                                           , "a-tp": "radio",    "radios":     ["No concerns with speech or day-to-day thinking", "People struggle to understand me (slurred/unclear) or my voice gets tired/hoarse", "I lose words or struggle to follow conversations and want strategies", "I forget steps for daily tasks (meds, appointments, meals) and want planning/memory supports"]},
  {"q-idx": 16 , "q-str": "In the past 2 weeks, have low mood, anxiety, or stress been present most days?"                                           , "a-tp": "radio",    "radios":     ["Yes", "No"]},
  {"q-idx": 17 , "q-str": "How much have these feelings interfered with daily life (sleep, appetite, concentration, routines, relationships)?"       , "a-tp": "radio",    "radios":     ["I clicked No to previous question", "A little — I still manage most things", "Quite a bit — often disrupts my day", "A lot — hard to manage most days"]},
  {"q-idx": 18 , "q-str": "Would you like social visits or engagement?"                                                                              , "a-tp": "radio",    "radios":     ["I'm fine without social visits", "Friendly conversation/check-ins", "Walks, fresh air, or hobbies with someone", "Just a brief wellness visit and safety scan"]},
  {"q-idx": 19 , "q-str": "Would support with alcohol use help you right now?"                                                                       , "a-tp": "radio",    "radios":     ["No", "Maybe — I'd like information or a plan", "Yes — I want help getting started"]},
  {"q-idx": 20 , "q-str": "Would you like a social worker to help at home with benefits/forms, resources, or care coordination?"                     , "a-tp": "radio",    "radios":     ["No", "Yes — help with paperwork/resources", "Yes — help coordinating care and services"]}
];
